# Generated by Django 4.1.5 on 2023-01-13 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 4, 59, 56, 360786, tzinfo=datetime.timezone.utc)),
        ),
    ]
