# Generated by Django 4.1.5 on 2023-01-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('update_dt',)},
        ),
    ]
